export const data = [
    {
      title: 'Product 1',
      subtitle: 'Subtitle for Product 1',
      description: 'This is a description for Product 1. It provides more details about the product.',
      imageUrl: 'https://example.com/product1.jpg',
    },
    {
      title: 'Product 2',
      subtitle: 'Subtitle for Product 2',
      description: 'This is a description for Product 2. It provides more details about the product.',
      imageUrl: 'https://example.com/product2.jpg',
    },
    {
      title: 'Product 3',
      subtitle: 'Subtitle for Product 3',
      description: 'This is a description for Product 3. It provides more details about the product.',
      imageUrl: 'https://example.com/product3.jpg',
    },
    {
      title: 'Product 4',
      subtitle: 'Subtitle for Product 4',
      description: 'This is a description for Product 4. It provides more details about the product.',
      imageUrl: 'https://example.com/product4.jpg',
    },
    {
      title: 'Product 5',
      subtitle: 'Subtitle for Product 5',
      description: 'This is a description for Product 5. It provides more details about the product.',
      imageUrl: 'https://example.com/product5.jpg',
    },
    {
      title: 'Product 6',
      subtitle: 'Subtitle for Product 6',
      description: 'This is a description for Product 6. It provides more details about the product.',
      imageUrl: 'https://example.com/product6.jpg',
    },
    {
      title: 'Product 7',
      subtitle: 'Subtitle for Product 7',
      description: 'This is a description for Product 7. It provides more details about the product.',
      imageUrl: 'https://example.com/product7.jpg',
    },
    {
      title: 'Product 8',
      subtitle: 'Subtitle for Product 8',
      description: 'This is a description for Product 8. It provides more details about the product.',
      imageUrl: 'https://example.com/product8.jpg',
    },
    {
      title: 'Product 9',
      subtitle: 'Subtitle for Product 9',
      description: 'This is a description for Product 9. It provides more details about the product.',
      imageUrl: 'https://example.com/product9.jpg',
    },
    {
      title: 'Product 10',
      subtitle: 'Subtitle for Product 10',
      description: 'This is a description for Product 10. It provides more details about the product.',
      imageUrl: 'https://example.com/product10.jpg',
    },
    {
      title: 'Product 11',
      subtitle: 'Subtitle for Product 11',
      description: 'This is a description for Product 11. It provides more details about the product.',
      imageUrl: 'https://example.com/product11.jpg',
    },
    {
      title: 'Product 12',
      subtitle: 'Subtitle for Product 12',
      description: 'This is a description for Product 12. It provides more details about the product.',
      imageUrl: 'https://example.com/product12.jpg',
    },
    {
      title: 'Product 13',
      subtitle: 'Subtitle for Product 13',
      description: 'This is a description for Product 13. It provides more details about the product.',
      imageUrl: 'https://example.com/product13.jpg',
    },
  ];