export const data = [
  {
    title: 'Product 1',
    subtitle: 'Subtitle for Product 1',
    description: 'This is a description for Product 1. It provides more details about the product.',
    imageUrl: 'https://example.com/product1.jpg',
  },
  {
    title: 'Product 2',
    subtitle: 'Subtitle for Product 2',
    description: 'This is a longer description for Product 2. It provides more detailed information about the product, including its features, benefits, and specifications.',
    imageUrl: 'https://example.com/product2.jpg',
  },
  {
    title: 'Product 3',
    subtitle: 'Subtitle for Product 3',
    description: 'Product 3 description.',
    imageUrl: 'https://example.com/product3.jpg',
  },
  {
    title: 'Product 4',
    subtitle: 'Subtitle for Product 4',
    description: 'This is a medium-length description for Product 4, providing some additional details about the product.',
    imageUrl: 'https://example.com/product4.jpg',
  },
  {
    title: 'Product 5',
    subtitle: 'Subtitle for Product 5',
    description: 'Product 5 is a high-quality product designed to meet your needs. It offers a range of features and benefits that make it stand out from the competition.',
    imageUrl: 'https://example.com/product5.jpg',
  },
  {
    title: 'Product 6',
    subtitle: 'Subtitle for Product 6',
    description: 'This product description is quite long and covers various aspects of Product 6, including its design, functionality, performance, and compatibility with other products or systems.',
    imageUrl: 'https://example.com/product6.jpg',
  },
  {
    title: 'Product 7',
    subtitle: 'Subtitle for Product 7',
    description: 'Short description for Product 7.',
    imageUrl: 'https://example.com/product7.jpg',
  },
  {
    title: 'Product 8',
    subtitle: 'Subtitle for Product 8',
    description: 'Product 8 is a versatile and reliable product that offers excellent value for money. With its user-friendly design and robust construction, it is suitable for a wide range of applications.',
    imageUrl: 'https://example.com/product8.jpg',
  },
  {
    title: 'Product 9',
    subtitle: 'Subtitle for Product 9',
    description: 'This is a concise description of Product 9.',
    imageUrl: 'https://example.com/product9.jpg',
  },
  {
    title: 'Product 10',
    subtitle: 'Subtitle for Product 10',
    description: 'Product 10 is a cutting-edge solution designed to revolutionize the way you work. With its advanced features and innovative technology, it offers unparalleled performance and efficiency.',
    imageUrl: 'https://example.com/product10.jpg',
  },
  {
    title: 'Product 11',
    subtitle: 'Subtitle for Product 11',
    description: 'This description provides an overview of Product 11, including its key features and benefits.',
    imageUrl: 'https://example.com/product11.jpg',
  },
  {
    title: 'Product 12',
    subtitle: 'Subtitle for Product 12',
    description: 'Product 12 is a high-performance product that delivers exceptional results. With its cutting-edge technology and user-friendly design, it is the perfect choice for professionals and enthusiasts alike.',
    imageUrl: 'https://example.com/product12.jpg',
  },
  {
    title: 'Product 13',
    subtitle: 'Subtitle for Product 13',
    description: 'A brief description of Product 13.',
    imageUrl: 'https://example.com/product13.jpg',
  },
];